//Types
export const HOSPITAL_LOADING = "HOSPITAL_LOADING";
export const HOSPITAL_LOADED = "HOSPITAL_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GENERAL_HOSPITAL_REDUCER = "GENERAL_HOSPITAL_REDUCER";
export const AUTH_ERROR = "AUTH_ERROR";
