//Types
export const SELLER_LOADING = "SELLER_LOADING";
export const SELLER_LOADED = "SELLER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GENERAL_SELLER_REDUCER = "GENERAL_SELLER_REDUCER";
export const AUTH_ERROR = "AUTH_ERROR";
